---
title: "BIOSTAT 203B HW1 Solutions"
author: "George Dewey UID: 704528320"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 2.3

The provided bash code provides the direct file path of the files located in the `/home/203bdata/mimic-iii/` directory.

```{bash}
for datafile in /home/203bdata/mimic-iii/*.csv
  do
    ls $datafile
  done
```

The number of lines in each csv file can can be generated with the following code:

```{bash, eval=F}
for datafile in /home/203bdata/mimic-iii/*.csv
  do
    awk 'END { print NR }' $datafile
  done
```

### Question 2.4

Display the first 10 lines of ADMISSIONS.csv with: 

```{bash}
head /home/203bdata/mimic-iii/ADMISSIONS.csv
```

From :
```{bash}
awk 'END { print NR }' /home/203bdata/mimic-iii/ADMISSIONS.csv
```
There are **58977** lines in ADMISSIONS.csv.

The number of unique patients in the dataset can be given by:
```{bash}
awk '{print $2}' /home/203bdata/mimic-iii/ADMISSIONS.csv | sort | uniq | wc -l
```

There are **58768** unique patients.

To obtain the possible values for each category, we can use 
```{bash, eval=FALSE}
awk -F ',' '{if (NR!=1) {print $N}}' /home/203bdata/mimic-iii/ADMISSIONS.csv | sort | uniq
```
 and change the column number `N`.
 
Thus for column 10 `INSURANCE` the possible values are:

```{bash}
awk -F ',' '{if (NR!=1) {print $10}}' /home/203bdata/mimic-iii/ADMISSIONS.csv | sort | uniq
```

For column 11 `LANGUAGE`:

```
"ALBA"
"AMER"
"*AMH"
"*ARA"
"ARAB"
"*ARM"
"* BE"
"*BEN"
"BENG"
"*BOS"
"*BUL"
"*BUR"
"CAMB"
"*CAN"
"CANT"
"CAPE"
"*CDI"
"*CHI"
"*CRE"
"*DEA"
"*DUT"
"ENGL"
"ETHI"
"*FAR"
"*FIL"
"FREN"
"* FU"
"*FUL"
"GERM"
"GREE"
"*GUJ"
"HAIT"
"HIND"
"*HUN"
"*IBO"
"ITAL"
"JAPA"
"*KHM"
"KORE"
"LAOT"
"*LEB"
"*LIT"
"*MAN"
"MAND"
"*MOR"
"*NEP"
"*PER"
"PERS"
"*PHI"
"POLI"
"PORT"
"PTUN"
"*PUN"
"*ROM"
"*RUS"
"RUSS"
"SERB"
"**SH"
"SOMA"
"*SPA"
"SPAN"
"** T"
"TAGA"
"*TAM"
"*TEL"
"THAI"
"**TO"
"*TOI"
"*TOY"
"TURK"
"*URD"
"URDU"
"VIET"
"*YID"
"*YOR"
```

For column 12 `RELIGION`:

```
"7TH DAY ADVENTIST"
"BAPTIST"
"BUDDHIST"
"CATHOLIC"
"CHRISTIAN SCIENTIST"
"EPISCOPALIAN"
"GREEK ORTHODOX"
"HEBREW"
"HINDU"
"JEHOVAH'S WITNESS"
"JEWISH"
"LUTHERAN"
"METHODIST"
"MUSLIM"
"NOT SPECIFIED"
"OTHER"
"PROTESTANT QUAKER"
"ROMANIAN EAST. ORTH"
"UNITARIAN-UNIVERSALIST"
"UNOBTAINABLE"
```

For column 13 `MARITAL_STATUS`:

```
"DIVORCED"
"LIFE PARTNER"
"MARRIED"
"SEPARATED"
"SINGLE"
"UNKNOWN (DEFAULT)"
"WIDOWED"
```

And for column 14 `ETHNICITY`:

```
"AMERICAN INDIAN/ALASKA NATIVE"
"AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE"
"ASIAN"
"ASIAN - ASIAN INDIAN"
"ASIAN - CAMBODIAN"
"ASIAN - CHINESE"
"ASIAN - FILIPINO"
"ASIAN - JAPANESE"
"ASIAN - KOREAN"
"ASIAN - OTHER"
"ASIAN - THAI"
"ASIAN - VIETNAMESE"
"BLACK/AFRICAN"
"BLACK/AFRICAN AMERICAN"
"BLACK/CAPE VERDEAN"
"BLACK/HAITIAN"
"CARIBBEAN ISLAND"
"HISPANIC/LATINO - CENTRAL AMERICAN (OTHER)"
"HISPANIC/LATINO - COLOMBIAN"
"HISPANIC/LATINO - CUBAN"
"HISPANIC/LATINO - DOMINICAN"
"HISPANIC/LATINO - GUATEMALAN"
"HISPANIC/LATINO - HONDURAN"
"HISPANIC/LATINO - MEXICAN"
"HISPANIC/LATINO - PUERTO RICAN"
"HISPANIC/LATINO - SALVADORAN"
"HISPANIC OR LATINO"
"MIDDLE EASTERN"
"MULTI RACE ETHNICITY"
"NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER"
"OTHER"
"PATIENT DECLINED TO ANSWER"
"PORTUGUESE"
"SOUTH AMERICAN"
"UNABLE TO OBTAIN"
"UNKNOWN/NOT SPECIFIED"
"WHITE"
"WHITE - BRAZILIAN"
"WHITE - EASTERN EUROPEAN"
"WHITE - OTHER EUROPEAN"
"WHITE - RUSSIAN"
```

### Question 3.1

After running this code:

```{bash, eval=FALSE}
for character in "Elizabeth" "Jane" "Lydia" "Darcy"
  do
    grep -oE $character pride_and_prejudice.txt | wc -l
  done
```

We obtain:

```
"Elizabeth" - 634
"Jane" - 294
"Lydia" - 170
"Darcy" - 417
```
Thus Elizabeth was the most mentioned.

### Question 3.2

The command `echo 'hello, world' > test1.txt` overwrites anything in the file `test1.txt` with the text "hello, world".  The other command `echo 'hello, world' >> test2.txt` appends the text "hello, world" to the file `test2.txt`.

### Question 3.3

The output returns the `$2-$3` lines of file `$1`.
The fields `$1`, `$2`, and `$3` serve as placeholders for the arguments the user must input to run the script.
The numeric arguments indicate the input positions for each argument (i.e. $1 is the first input, $2 is the second, etc.)

In this case, the output for `./middle.sh pride_and_prejudice.txt 20 5` was lines 15-20 of the text:

```
Author: Jane Austen

Editor: R. W. (Robert William) Chapman
```

The purpose of the first line of the script is to tell the operating system what shell to run the script in (in this case the `sh` shell).






